apiVersion: v2
name: pganalyze-collector
version: 0.69.0
appVersion: "v0.69.0"
type: application
description: pganalyze statistics collector
home: https://pganalyze.com/
sources:
  - https://github.com/pganalyze/collector
