apiVersion: v2
name: pganalyze-collector
version: 0.68.3
appVersion: "v0.68.3"
type: application
description: pganalyze statistics collector
home: https://pganalyze.com/
sources:
  - https://github.com/pganalyze/collector
